"""Physical plant: a permanent-magnet linear actuator -- a slug with NO iron, just a
magnet, sliding in a tube past N air-core coil stations. Linear analog of plant.py's
pendulum (see docs/DESIGN_LINEAR.md): drop the gravity restoring term, replace angle/
inertia with position/mass, and sum each coil station's position-dependent coupling.

Each coil's force is the sum of two terms, both reused unchanged from plant.py -- kept
as TWO terms rather than collapsing to one, because a slug's construction is a config
choice, not a fixed assumption:
  - f_current  (reluctance branch): attract-only, quadratic-with-saturation, from a
    ferromagnetic slug body. `CoilStation.Cmag` defaults to 0.0 -- this build's slug has
    NO iron, only the magnet, so this term is off by default. Coil-core saturation was
    never part of this term regardless (the coils are air-core, so their own B-H curve is
    linear; `i_sat` models the reluctance PATH's -- the slug's iron, if any -- saturating).
  - PM branch: linear and SIGNED, from the slug's magnet interacting with the coil's
    field -- i>0 attracts, i<0 repels. Geometry-built coils use a winding-volume K(x)
    table; hand-authored legacy coils fall back to q_shape*k_a. The same K(x) produces
    reciprocal back-EMF e=K(x)v.

CoilStation exposes the same `.Cmag` / `.i_sat` field names PendulumParams does, so
f_current's duck-typed contract is satisfied without touching its signature (it is public
API, used directly by tests).
"""

from __future__ import annotations

import math
from bisect import bisect_right
from dataclasses import dataclass, field
from typing import Sequence

from .plant import (
    f_current,
    q_shape,
    resistance_at_temperature,
    thermal_step,
)


@dataclass(frozen=True)
class CoilStation:
    position_m: float
    x_c: float = 0.020     # m, coupling half-width -- linear analog of theta_c
    # Reluctance branch (see module docstring): 0.0 assumes an iron-free, pure-PM slug.
    # Set nonzero to model a hybrid (ferromagnetic + embedded magnet) slug instead.
    Cmag: float = 0.0      # N per A^2 -- same field name as PendulumParams (f_current duck-types on it)
    i_sat: float = 6.0     # A, saturation current (of the slug's iron reluctance path, if any)
    # PM-branch gain (N/A, linear/signed) from the slug's magnet -- see module docstring.
    # A placeholder pending real calibration, like every other constant in this model.
    k_a: float = 0.20
    # Electrical properties of the winding itself (air-core: R, L are constant WITH
    # RESPECT TO CURRENT -- no saturation-driven inductance drop; R does still vary with
    # temperature, see thermal fields below). resistance_ohm is the value AT
    # LinearActuatorParams.ambient_temperature_c's reference point (matching
    # coil_design.wind_coil's `temperature_c` param) -- the actual, temperature-adjusted
    # resistance used at runtime is coil_resistance(). See LinearActuatorParams.
    # current_loop for how current itself gets used -- ignored entirely under the "ideal"
    # (instantaneous current) mode.
    resistance_ohm: float = 1.2   # ohm
    inductance_h: float = 0.004   # H
    # One-node thermal model (see thermal_step / coil_temperature_step below), active only
    # when LinearActuatorParams.thermal_model is True. thermal_mass_j_per_k is derivable
    # from the winding's own copper volume (coil_design.wind_coil does this) -- a
    # lower bound on the real thermal mass, since it ignores bobbin/potting/frame.
    # thermal_resistance_k_per_w has no geometry-derived formula in this model (it depends
    # on convection/mounting this project has no basis to estimate) -- a placeholder
    # constant like every other uncalibrated value here, pending a real measurement.
    thermal_mass_j_per_k: float = 12.0     # J/K
    thermal_resistance_k_per_w: float = 8.0  # K/W
    # Optional position-dependent PM motor-constant table generated by coil_design.
    # The coordinate is slug position minus coil-center position.  Values have units
    # N/A == V/(m/s), so this exact same table is used for both F=K(x)i and
    # e_back=K(x)v.  Empty tuples preserve the legacy analytic q_shape*k_a model for
    # hand-authored configs.
    coupling_positions_m: tuple[float, ...] = ()
    coupling_n_per_a: tuple[float, ...] = ()


@dataclass(frozen=True)
class GateStation:
    position_m: float
    w_eff: float = 0.004   # m, effective blocked width -- linear analog of dalpha



def default_coil_stations(pitch: float = 0.05, n: int = 5, **kwargs) -> tuple[CoilStation, ...]:
    return tuple(CoilStation(position_m=k * pitch, **kwargs) for k in range(n))



def default_gate_stations(pitch: float = 0.05, n_coils: int = 5, **kwargs) -> tuple[GateStation, ...]:
    """One entry gate before coil 0, then one gate at the midpoint of each adjacent coil
    pair -- n_coils gates for n_coils coils. See docs/DESIGN_LINEAR.md section 2 for why the
    boundary gate goes at entry (bootstrap confirmation) rather than exit."""
    positions = [-0.5 * pitch] + [(k + 0.5) * pitch for k in range(n_coils - 1)]
    return tuple(GateStation(position_m=x, **kwargs) for x in positions)


@dataclass
class LinearActuatorParams:
    mass_kg: float = 0.20
    damping_n_per_mps: float = 0.05     # direct viscous coeff -- no restoring term to derive a Q from
    coils: tuple[CoilStation, ...] = field(default_factory=default_coil_stations)
    gates: tuple[GateStation, ...] = field(default_factory=default_gate_stations)
    end_of_travel: str = "coast"        # "coast" | "brake_hold"
    # Constant forward force from a pressurized reservoir behind the slug (N), independent
    # of any coil current. Default 0.0 reproduces the unpressurized model exactly. See
    # docs/DESIGN_LINEAR.md's "pressurized tube" section: this is what removes the one
    # genuinely fragile case in the coil-only design -- a slug resting EXACTLY at a coil's
    # center has zero force from that coil at any current (q_shape(0, x_c) == 0), so firing
    # it does nothing; a nonzero bias guarantees the net force there is nonzero regardless,
    # so the slug can never be stuck in true static equilibrium. Modeled as constant rather
    # than an ideal-gas P*V=const decay with position -- a reasonable first approximation
    # for a regulated supply or a large reservoir; a decaying-pressure model is a natural
    # refinement if you're modeling a small fixed-volume charge instead.
    pressure_bias_n: float = 0.0
    # Electrical model. "ideal" (default) treats current as instantaneously commandable --
    # the pre-inductance behavior, and still the right choice for fast/simple sims. "rl"
    # integrates each coil's actual current from its own RL circuit (see
    # coil_current_step()), which solves for the exact constant voltage that reaches
    # whatever the supervisor's raised-cosine profile asks for over one tick, rail-limited
    # -- current then lags the ideal profile by roughly the coil's L/R time constant,
    # including a nonzero decay tail after a "hard cut" (there is no negative supply rail
    # in a single half-bridge driver to force it to zero faster). See
    # docs/DESIGN_LINEAR.md's electrical-dynamics section.
    current_loop: str = "ideal"           # "ideal" | "rl"
    bus_voltage_v: float = 12.0
    # False (default): a single half-bridge driver, matching the soft-iron reference
    # build -- can only ever source i>=0. True: an H-bridge, able to source negative
    # current too. Only matters under current_loop="rl" -- "ideal" mode has no hardware
    # model at all, so a signed target is achieved instantly either way. Repel-pumping
    # (StepperSupervisor's departure-side thrust, docs/DESIGN_LINEAR.md) needs this True
    # to actually take effect under "rl"; under "ideal" it works regardless.
    driver_bipolar: bool = False
    # One-node-per-coil thermal model (docs/DESIGN_LINEAR.md's thermal section): False
    # (default) reproduces the exact prior behavior -- every coil's resistance is its
    # fixed resistance_ohm value, forever, at every current. True tracks each coil's own
    # winding temperature (see coil_temperature_step()) from its own i^2*R dissipation,
    # feeding the resulting R(T) back into "rl" mode's electrical dynamics (coil_resistance())
    # -- so a design that only looks fast because it never pays a heating penalty stops
    # looking that way. Off by default because it's new and the design-space search
    # (optimize_design.py) hasn't been re-validated with it on yet.
    thermal_model: bool = False
    ambient_temperature_c: float = 20.0
    # Physical scoring/measurement plane. None resolves beyond the final modeled
    # coupling support (or 4*x_c for a legacy analytic Gaussian lobe).
    exit_position_m: float | None = None

    @property
    def resolved_exit_position_m(self) -> float:
        if self.exit_position_m is not None:
            return self.exit_position_m
        if not self.coils:
            return 0.0
        last = self.coils[-1]
        coupling_extent = (last.coupling_positions_m[-1]
                           if last.coupling_positions_m else 4.0 * last.x_c)
        return last.position_m + coupling_extent


@dataclass(frozen=True)
class ElectricalStep:
    """One exact constant-coefficient RL step plus energy integrals.

    ``current_integral_as`` is integral(i dt), and ``current_sq_integral_a2s``
    is integral(i^2 dt).  Their energy products close exactly for the electrical
    model before mechanical discretization error is introduced.
    """

    current_a: float
    applied_voltage_v: float
    back_emf_v: float
    current_integral_as: float
    current_sq_integral_a2s: float
    bus_energy_j: float
    copper_loss_j: float
    transduced_energy_j: float
    field_energy_delta_j: float
    residual_j: float



def pm_coupling_n_per_a(x_relative_m: float, coil: CoilStation) -> float:
    """Position-dependent PM motor constant K(x), in N/A == V/(m/s).

    Geometry-built coils carry a winding-volume-integrated lookup table.  Legacy
    hand-authored coils fall back to the original normalized analytic lobe.
    """
    xs = coil.coupling_positions_m
    ys = coil.coupling_n_per_a
    if not xs or not ys:
        return q_shape(x_relative_m, coil.x_c) * coil.k_a
    if len(xs) != len(ys):
        raise ValueError("coupling_positions_m and coupling_n_per_a must have equal length")
    if x_relative_m < xs[0] or x_relative_m > xs[-1]:
        return 0.0
    if x_relative_m == xs[-1]:
        return ys[-1]
    hi = bisect_right(xs, x_relative_m)
    lo = max(0, hi - 1)
    hi = min(hi, len(xs) - 1)
    if lo == hi or xs[hi] == xs[lo]:
        return ys[lo]
    frac = (x_relative_m - xs[lo]) / (xs[hi] - xs[lo])
    return ys[lo] + frac * (ys[hi] - ys[lo])


def pm_back_emf_v(x: float, v: float, coil: CoilStation) -> float:
    """Reciprocal PM back-EMF using the same K(x) as mechanical force."""
    return pm_coupling_n_per_a(x - coil.position_m, coil) * v


def net_force(x: float, currents: Sequence[float], p: LinearActuatorParams) -> float:
    """Sum of every energized coil's local, odd, zero-at-its-own-center coupling toward
    that coil's position -- reluctance term (f_current) plus PM term (f_current_pm),
    added together per coil -- plus the constant pressure bias (if any). Reuses
    q_shape/f_current/f_current_pm verbatim -- only the anchor point (each coil's own
    position_m) differs from the pendulum's single anchor at theta=0."""
    total = p.pressure_bias_n
    for coil, i_k in zip(p.coils, currents):
        if i_k == 0.0:
            continue
        x_rel = x - coil.position_m
        q = q_shape(x_rel, coil.x_c)
        total += q * f_current(i_k, coil)
        total += pm_coupling_n_per_a(x_rel, coil) * i_k
    return total



def undamped_accel(x: float, currents: Sequence[float], p: LinearActuatorParams) -> float:
    """Acceleration from position-dependent coil/pressure forces only."""
    return net_force(x, currents, p) / p.mass_kg



def accel(x: float, v: float, currents: Sequence[float], p: LinearActuatorParams) -> float:
    return undamped_accel(x, currents, p) - (p.damping_n_per_mps / p.mass_kg) * v



def step(x: float, v: float, currents: Sequence[float], dt: float, p: LinearActuatorParams):
    """One damped velocity-Verlet step -- same accuracy upgrade as plant.step().

    The force field is evaluated at both ends of the drift, while linear viscous damping is
    applied as exact half-step exponential factors.  This is still cheap and deterministic,
    but reduces timestep sensitivity versus first-order semi-implicit Euler for fast/light
    candidate designs and near narrow coil lobes.
    """
    if dt == 0.0:
        return x, v

    gamma = p.damping_n_per_mps / p.mass_kg if p.mass_kg > 0.0 else 0.0
    damp_half = math.exp(-0.5 * gamma * dt) if gamma > 0.0 else 1.0

    v_d = v * damp_half
    a0 = undamped_accel(x, currents, p)
    v_half = v_d + 0.5 * a0 * dt
    x_new = x + v_half * dt
    a1 = undamped_accel(x_new, currents, p)
    v_new = (v_half + 0.5 * a1 * dt) * damp_half
    return x_new, v_new



def coil_electrical_step(i_actual: float, i_target: float, coil: CoilStation,
                         bus_voltage_v: float, dt: float, bipolar: bool = False,
                         resistance_ohm_override: float | None = None,
                         back_emf_v: float = 0.0) -> ElectricalStep:
    """Advance current and return an exact RL energy ledger for one tick."""
    r = coil.resistance_ohm if resistance_ohm_override is None else resistance_ohm_override
    l = coil.inductance_h
    if r <= 0.0 or l <= 0.0 or dt < 0.0 or bus_voltage_v < 0.0:
        raise ValueError("R, L and bus voltage must be positive and dt must be non-negative")
    if dt == 0.0:
        return ElectricalStep(i_actual, 0.0, back_emf_v, 0.0, 0.0,
                              0.0, 0.0, 0.0, 0.0, 0.0)

    tau = l / r
    decay = math.exp(-dt / tau)
    # Invert the exact RL response including reciprocal motional EMF.  The applied
    # bridge voltage must overcome both Ri and K(x)v.
    tracking_voltage = r * (i_target - i_actual * decay) / (1.0 - decay)
    v_needed = back_emf_v + tracking_voltage
    v_min = -bus_voltage_v if bipolar else 0.0
    v_applied = max(v_min, min(bus_voltage_v, v_needed))
    v_effective = v_applied - back_emf_v
    i_ss = v_effective / r
    delta = i_actual - i_ss
    i_unconstrained = i_ss + delta * decay
    integration_dt = dt
    integration_decay = decay
    if not bipolar and i_unconstrained < 0.0 and i_ss < 0.0 and delta > 0.0:
        # A unipolar freewheel path prevents reversal.  Integrate the exact RL
        # trajectory only until its zero crossing, then hold i=0 for the rest.
        integration_decay = -i_ss / delta
        integration_dt = -tau * math.log(integration_decay)
        i_new = 0.0
    else:
        i_new = max(0.0, i_unconstrained) if not bipolar else i_unconstrained

    int_i = i_ss * integration_dt + delta * tau * (1.0 - integration_decay)
    int_i2 = (
        i_ss * i_ss * integration_dt
        + 2.0 * i_ss * delta * tau * (1.0 - integration_decay)
        + delta * delta * 0.5 * tau * (1.0 - integration_decay * integration_decay)
    )

    bus_energy = v_applied * int_i
    copper_loss = r * int_i2
    transduced = back_emf_v * int_i
    field_delta = 0.5 * l * (i_new * i_new - i_actual * i_actual)
    residual = bus_energy - copper_loss - transduced - field_delta
    return ElectricalStep(i_new, v_applied, back_emf_v, int_i, int_i2,
                          bus_energy, copper_loss, transduced, field_delta, residual)


def coil_current_step(i_actual: float, i_target: float, coil: CoilStation,
                       bus_voltage_v: float, dt: float, bipolar: bool = False,
                       resistance_ohm_override: float | None = None,
                       back_emf_v: float = 0.0) -> float:
    """Advance one coil's ACTUAL current toward i_target over one control tick, through
    its own RL circuit rather than snapping to the target instantly. Modeled as an
    idealized current-mode PWM controller: solve for the exact CONSTANT voltage that would
    drive current from i_actual to i_target over exactly this dt (inverting
    the RL closed form, including ``back_emf_v``), then clamp that to what the driver rail can
    actually supply -- [0, bus_voltage_v] for a single half-bridge (bipolar=False) or
    [-bus_voltage_v, bus_voltage_v] for an H-bridge (bipolar=True). When the exact voltage
    is within the rail, this reaches i_target exactly after one step, at ANY dt, with no
    overshoot; when it isn't, applying the rail limit for the whole step is the correctly
    rail-limited (not overshooting) response.

    This replaced a cruder two-state (full-on/full-off) bang-bang model. Bang-bang chatters
    around the target rather than settling, which is a minor cosmetic issue normally -- but
    for a LOW-resistance coil under a HIGH bus voltage (few turns, thick winding: a real,
    reachable combination once turns/dimensions/voltage are all free design knobs), the
    bang-bang steady-state current V/R can be orders of magnitude above the intended
    target. Discovered via a dt-refinement check during development: reported exit speed
    for such a design kept DROPPING as dt shrank instead of converging (no amount of
    sub-stepping fixed it, because the failure was the control law's steady-state target
    being wrong by orders of magnitude, not an integration-accuracy problem). Solving for
    the exact tracking voltage removes the failure mode outright: it can only ever reach
    for the RIGHT target, rail-limited, never an implied one thousands of times larger.
    bipolar=False means a negative i_target still can't actually be reached (v_min=0), same
    as before -- StepperSupervisor's departure-side repel-pumping still needs bipolar=True
    to take effect under "rl" (under "ideal", with no hardware model at all, repel already
    works regardless of this flag).

    resistance_ohm_override, if given, is used instead of coil.resistance_ohm for BOTH
    the voltage solve and the rl_current_step update -- the hook LinearActuatorParams.
    thermal_model uses to feed each coil's temperature-adjusted resistance (see
    coil_resistance()) back into its own electrical dynamics, without changing behavior
    at all when omitted (the default, exactly reproducing the fixed-resistance model).
    """
    return coil_electrical_step(
        i_actual, i_target, coil, bus_voltage_v, dt, bipolar=bipolar,
        resistance_ohm_override=resistance_ohm_override,
        back_emf_v=back_emf_v,
    ).current_a



def kinetic_energy(v: float, p: LinearActuatorParams) -> float:
    return 0.5 * p.mass_kg * v * v


def coil_resistance(coil: CoilStation, temperature_c: float,
                    reference_temperature_c: float = 20.0) -> float:
    """A coil's actual resistance at its current winding temperature -- coil.resistance_ohm
    is the value at LinearActuatorParams.ambient_temperature_c (matching coil_design.
    wind_coil's own `temperature_c` build-time parameter), scaled by the same copper
    resistivity-vs-temperature law used everywhere else in this project
    (plant.resistance_at_temperature). Only meaningful when LinearActuatorParams.
    thermal_model is True; otherwise every coil stays at ambient by construction (see
    LinearSimulator.run())."""
    return resistance_at_temperature(coil.resistance_ohm, temperature_c,
                                     ref_temperature_c=reference_temperature_c)


def coil_temperature_step(temperature_c: float, current_a: float, resistance_ohm: float,
                           coil: CoilStation, ambient_c: float, dt: float) -> float:
    """Advance one coil's winding temperature by one control tick, from its own i^2*R
    dissipation, via plant.thermal_step's exact one-node thermal model. Takes the
    dissipating current AND resistance explicitly (rather than re-deriving resistance from
    coil + temperature_c internally) so the caller can pass exactly the resistance value
    that current was actually driven against this tick, whatever LinearActuatorParams.
    current_loop had in effect -- keeping power = current_a**2 * resistance_ohm consistent
    with what really happened electrically, not a second, possibly-stale estimate of it."""
    power_w = current_a * current_a * resistance_ohm
    return thermal_step(temperature_c, power_w, coil.thermal_mass_j_per_k,
                        coil.thermal_resistance_k_per_w, ambient_c, dt)


def coil_temperature_step_mean_square(temperature_c: float, mean_square_current_a2: float,
                                      resistance_ohm: float, coil: CoilStation,
                                      ambient_c: float, dt: float) -> float:
    """Thermal update using the exact/averaged integral of i² over the tick."""
    power_w = max(0.0, mean_square_current_a2) * resistance_ohm
    return thermal_step(temperature_c, power_w, coil.thermal_mass_j_per_k,
                        coil.thermal_resistance_k_per_w, ambient_c, dt)
